# Generated by Django 3.2.23 on 2023-11-06 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_ingredients_recipe_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
